name: mobile
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  schedule_repository:
    path: packages/schedule_repository
  api_client:
    path: packages/api_client
  models:
    path: packages/models
  bloc: ^8.1.2
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  formz: ^0.6.1
  geolocator: ^10.1.0
  meta: ^1.9.1
  permission_handler: ^11.0.1
  yandex_mapkit: ^3.3.3
  flutter_gen: ^5.3.2
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  table_calendar: ^3.0.9
  flutter_week_view: ^1.3.0
  intl: ^0.18.1
  yandex_geocoder: ^2.1.0
  draggable_bottom_sheet: ^1.0.2
  expandable_bottom_sheet: ^1.1.1+1
  flutter_native_splash: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: false
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: false
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: false
    image_path: "path/to/image.png"

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  integrations:
    flutter_svg: true

  assets:
    enabled: true

    outputs:
      class_name: MyAssets
      package_parameter_enabled: false
      # Assets.imagesChip
      # style: camel-case

      # Assets.images_chip
      # style: snake-case

      # Assets.images.chip (default style)
      style: dot-delimiter

    #exclude:
    #  - assets/images/chip3/chip3.jpg
    #  - pictures/chip5.jpg
    #  - assets/flare/

  fonts:
    enabled: true
    outputs:
      class_name: MyFonts

  colors:
    enabled: true
    outputs:
      class_name: MyColors
    inputs:
      - assets/color/colors.xml

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
